// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7IEdF8w8m3LpGovP573gSdBLVEts0euY',
    appId: '1:305192039236:web:4238c7127f41838a925d11',
    messagingSenderId: '305192039236',
    projectId: 'ai-ambulance-dispatch-daa1a',
    authDomain: 'ai-ambulance-dispatch-daa1a.firebaseapp.com',
    storageBucket: 'ai-ambulance-dispatch-daa1a.firebasestorage.app',
    measurementId: 'G-SY53Q002RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsownvT-nvn3kbcWg1OZCeDN9IZuhoapo',
    appId: '1:305192039236:android:0d5f695af7853998925d11',
    messagingSenderId: '305192039236',
    projectId: 'ai-ambulance-dispatch-daa1a',
    storageBucket: 'ai-ambulance-dispatch-daa1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqEnlvnT0o69LDy5pBcKQe4wH02NdEZEg',
    appId: '1:305192039236:ios:e28ae37328536469925d11',
    messagingSenderId: '305192039236',
    projectId: 'ai-ambulance-dispatch-daa1a',
    storageBucket: 'ai-ambulance-dispatch-daa1a.firebasestorage.app',
    iosBundleId: 'com.example.aiAmbulanceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqEnlvnT0o69LDy5pBcKQe4wH02NdEZEg',
    appId: '1:305192039236:ios:e28ae37328536469925d11',
    messagingSenderId: '305192039236',
    projectId: 'ai-ambulance-dispatch-daa1a',
    storageBucket: 'ai-ambulance-dispatch-daa1a.firebasestorage.app',
    iosBundleId: 'com.example.aiAmbulanceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7IEdF8w8m3LpGovP573gSdBLVEts0euY',
    appId: '1:305192039236:web:4238c7127f41838a925d11',
    messagingSenderId: '305192039236',
    projectId: 'ai-ambulance-dispatch-daa1a',
    authDomain: 'ai-ambulance-dispatch-daa1a.firebaseapp.com',
    storageBucket: 'ai-ambulance-dispatch-daa1a.firebasestorage.app',
    measurementId: 'G-SY53Q002RH',
  );
}
